### ISSUE TITLE
【依頼】chat-space挙動確認

### ISSUE THREAD

**Issue by makoto1026** [makoto1026/chat-space#10]
# IPアドレス
18.178.250.136

よろしくお願いします！

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by makoto1026** [comment]
ありがとうございます!!
個人アプリも頑張ります!!
